### ISSUE TITLE
Ошибка запуска проекта

### ISSUE THREAD

**Issue by ValeryStatinov** [YankinaDarya/MIPT-react-homeworks#3]
https://github.com/YankinaDarya/MIPT-react-homeworks/blob/e7baa58a1d8c9276bb2d847593f8854fc82e44b3/src/components/TodoList/TodoList.jsx#L2

импортируемого файла не существует, поэтому проект не запускается

**Comment by YankinaDarya** [comment]
Я удалила эту строчку, теперь должен загружаться. Там был пустой файл, и он не добавился на гитхаб.
